# Generated by Django 4.2.20 on 2025-03-08 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('brake_inspection', 'Brake Inspection'), ('tire_replacement', 'Tire Replacement'), ('engine_diagnostics', 'Engine Diagnostics'), ('general_service', 'General Service'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('date_performed', models.DateField(default=django.utils.timezone.now)),
                ('technician', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='vehicles.vehicle')),
            ],
        ),
    ]
